type: object
definitions:
  reference:
    type: object
    properties:
      name:
        type: string
        required: true
      ref:
        type: string
        readonly: true

properties:
  components:
    type: array
    required: true
    items:
      $ref: '#/definitions/reference'
  id:
    type: number
    readonly: true
  name:
    type: string
    required: true
  ref:
    type: string
    readonly: true
  uncommitted:
    type: boolean
    readonly: true
