definitions:
  parent:
    properties:
      matpath: {readonly: true, type: string}
      name: {required: true, type: string}
      ref: {readonly: true, type: string}
    type: object
  reference:
    properties:
      name: {required: true, type: string}
      ref: {readonly: true, type: string}
    type: object

properties:
  children:
    type: array
    default: []
    items: {$ref: '#/definitions/reference'}

  hosts:
    type: array
    default: []
    items: {$ref: '#/definitions/reference'}

  id:
    type: number
    readonly: true

  is_leaf:
    type: boolean
    readonly: true

  matpath:
    type: string
    readonly: true

  name:
    type: string
    required: true

  ref:
    type: string
    readonly: true

  parent:
    $ref: '#/definitions/parent'
    type: [object, 'null']

  uncommitted:
    readonly: true
    type: boolean

type: object
