type: object
definitions:
  reference:
    type: object
    properties:
      name:
        type: string
        required: true
      ref:
        type: string
        readonly: true
  node:
    type: object
    properties:
      host:
        type: object
        properties:
          ip: {type: string, required: true}
          name: {type: string}
          ref: {type: string, readonly: true}
      slave_port:
        type: number
        readonly: true

properties:
  activated:
    type: boolean
    default: true
  id:
    type: number
    readonly: true
  monitors:
    type: array
    items:
      $ref: '#/definitions/reference'
  name:
    type: string
    required: true
  nodes:
    type: array
    items:
      $ref: '#/definitions/node'
    required: true
  passive:
    type: boolean
    default: false
  ref:
    type: string
    readonly: true
  roles:
    type: array
    items:
      $ref: '#/definitions/reference'
    readonly: true
  ssh_forward:
    type: boolean
    default: true
  uncommitted:
    type: boolean
    readonly: true
