type: object
definitions:
  reference:
    type: object
    properties:
      name: {type: string, required: true}
      ref: {type: string, readonly: true}
  variable:
    type: object
    properties:
      name: {type: string}
      value: {type: string}
properties:
  namespace: {type: string}
  master: {type: boolean}
  name: {type: string}
  active: {type: boolean}
  notificationprofiles:
    type: array
    items: {$ref: '#/definitions/reference'}
  id: {type: number, readonly: true}
  uncommitted: {type: boolean, readonly: true}
  command: {type: string}
  contact_variables: {type: string}
  variables:
    type: array
    items: {$ref: '#/definitions/variable'}
