type: object
definitions:
  reference:
    type: object
    properties:
      name: {type: string, required: true}
      ref: {type: string, readonly: true}

properties:
  name: {type: string, required: true}
  id: {type: number, readonly: true}
  servicechecks:
    type: array
    altname: service_checks
    items: {$ref: '#/definitions/reference'}
    default: []
  uncommitted: {type: boolean, readonly: true}
  ref: {type: string, readonly: true}
