type: object
definitions:
  reference:
    type: object
    properties:
      name: {type: string, required: true}
      ref: {type: string, readonly: true}

properties:
  all_hostgroups:
    altname: all_host_groups
    type: boolean
    default: False
  all_keywords:
    altname: all_hashtags
    type: boolean
    default: False
  all_servicegroups:
    altname: all_service_groups
    type: boolean
    default: False
  host_notification_options:
    type: string
    default: d,r,f
  hostgroups:
    altname: host_groups
    type: array
    items: {$ref: '#/definitions/reference'}
  id: {type: number, readonly: true}
  keywords:
    altname: hashtags
    type: array
    items: {$ref: '#/definitions/reference'}
  name: {type: string, required: true}
  notification_level: {type: number, default: 1}
  notification_period: {$ref: '#/definitions/reference'}
  role: {$ref: '#/definitions/reference'}
  service_notification_options: {type: string, default: w,c,r,u,f}
  servicegroups:
    altname: service_groups
    type: array
    items: {$ref: '#/definitions/reference'}
  uncommitted: {type: boolean, readonly: true}
  all_business_components: 
    default: False
    type: boolean
  all_business_services:
    default: False
    type: boolean
  business_component_availability_below:
    default: 99.999
    type: number
  business_component_options: 
    default: 'f,i'
    type: string
  business_component_renotification_interval: 
    default: 1800
    type: number
  business_components:
    type: array
    items: {$ref: '#/definitions/reference'}
  business_service_availability_below:
    default: 99.999
    type: number
  business_service_options:
    default: 'o,i'
    type: string
  business_service_renotification_interval: 
    default: 1800
    type: number
  business_services: 
    type: array
    items: {$ref: '#/definitions/reference'}
  include_component_notes: 
    default: False
    type: boolean
  include_service_notes: 
    default: False
    type: boolean
  notification_level_stop: 
    default: 0
    type: number
  notificationmethods:
    type: array
    items: {$ref: '#/definitions/reference'}
    altname: notification_methods
  ref: 
    type: string
    readonly: True
