type: object
definitions:
  reference:
    type: object
    properties:
      name: {type: string, required: true}
      ref: {type: string, readonly: true}

properties:
  description: {type: string}
  id: {type: number, readonly: true}
  name: {type: string, required: true}
  primary_role: {$ref: '#/definitions/reference', required: true}
  priority: {type: number, readonly: true}
  ref: {type: string, readonly: true}
